### ISSUE TITLE
Z argument transform

### ISSUE THREAD

**Issue by jokoast** [KirillMysnik/obs-ws-rc#4]
In the transformation request there isn't the Z argument, how can we set the Z position of the item ?

But a very good job ! I'll use it soon.

**Comment by jokoast** [comment]
My bad, sorry. I just saw the protocol you used and there is no Z argument.

Good job. I'll post an "issue" in the other repo.

**Comment by KirillMysnik** [comment]
Hey there. Yep, obs-ws-rc simply wraps [obs-websocket's protocol](https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setsceneitemtransform).
However, our version of that protocol is horribly outdated.

Thanks for your feedback!

**Comment by jokoast** [comment]
Yeah but the obs-websocket's protocol doesn't have the Z positionning feature.

Just in case, do you know a way to script item's movement X,Y,Z, transform (%X , %Y) and hide items ? To make a ""switch webcam" effect when switching POV's in FPS streams ?

**Comment by KirillMysnik** [comment]
I'm not sure what Z axis would do, if we're talking about `SetSceneItemTransform`. It just scales the source horizontally (X) and vertically (Y). Also it can rotate the source.

I suppose your question doesn't belong to obs-websocket repo neither, because they just provide an API to OBS's own features. Sounds more like a question for [OBS Project forum](https://obsproject.com/forum/).

And for hiding items: try different scenes. I think what you're trying to do should be done via scene switching. That will also let you use built-in scene switching transitions.
